name: genrator_11
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  get: ^4.6.6
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_lints: ^5.0.0

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#ffffff" # Optional: for Android adaptive icons
  adaptive_icon_foreground: "assets/logo.jpg" # Optional: for Android adaptive icons
  min_sdk_android: 21 # Optional: Android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/